.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. matcoin_qt test_matcoin_qt
clean: FORCE
	$(MAKE) -C .. matcoin_qt_clean test_matcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_matcoin_qt_check
matcoin-qt matcoin-qt.exe: FORCE
	 $(MAKE) -C .. matcoin_qt
